import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { ReactNode } from "react";
import Counter from "@/components/molecules/counter";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<div
					style={{
						display: "flex",
						gap: "10px",
					}}
				>
					<Link href="/products">Products</Link>
					<Link href="/game">Game</Link>

					<Link href="/articles">Articles</Link>

					<Link href="/users">Users</Link>
					<Counter />
				</div>
				{children}
			</body>
		</html>
	);
}
